[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 8.0

normal = { family = "FantasqueSansM Nerd Font", style = "Regular"}
italic = { family = "FantasqueSansM Nerd Font", style = "Italic"}
bold = { family = "FantasqueSansM Nerd Font", style = "Bold"}

[window]
dynamic_padding = false
opacity = 0.94
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 3
y = 3

[window.position]
x = 35
y = 0

# Colors (Solarized Dark)

# Default colors
[colors.primary]
background = '#00141a'
foreground = '#839495'

# Normal colors
[colors.normal]
black   = '#00141a'
red     = '#dc312e'
green   = '#859900'
yellow  = '#b38600'
blue    = '#278bd3'
magenta = '#d33682'
cyan    = '#2aa298'
white   = '#ede7d4'

# Bright colors
[colors.bright]
black   = '#002d38'
red     = '#f65351'
green   = '#b7fa00'
yellow  = '#ffbf00'
blue    = '#47adf5'
magenta = '#f254a1'
cyan    = '#2beede'
white   = '#fdf6e2'
