[cursor.style]
shape = "Block"

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]

[env]
TERM = "alacritty"

[font]
size = 10.5

normal = { family = "PsudoFont Liga Mono", style = "Regular"}
italic = { family = "PsudoFont Liga Mono", style = "Italic"}
bold = { family = "PsudoFont Liga Mono", style = "Bold"}

[window]
# dynamic_padding = false
opacity = 0.9
blur = true
# title = "Rahman"
# dynamic_title = true
decorations = "None"

[window.padding]
x = 7
y = 4

[window.dimensions]
columns = 166
lines = 38

[window.position]
x = 10
y = 30

# Colors (Solarized Osaka)
# HSL convert HEX using https://colordesigner.io/

# Default colors
[colors.primary]
background = '#00141a' #color.base04
foreground = '#839495' #color.fg

# Normal colors
[colors.normal]
black   = '#00141a' #color.base04
red     = '#dc312e' #color.red
green   = '#859900' #color.green
yellow  = '#b38600' #color.yellow
blue    = '#278bd3' #color.blue
magenta = '#d33682' #color.magenta
cyan    = '#2aa298' #color.cyan
white   = '#ede7d4' #color.base2

# Bright colors
[colors.bright]
black   = '#002d38' #color.base03
red     = '#f65351' #color.red300
green   = '#b7fa00' #color.green300
yellow  = '#ffbf00' #color.yellow300
blue    = '#47adf5' #color.blue300
magenta = '#f254a1' #color.magenta300
cyan    = '#2beede' #color.cyan300
white   = '#fdf6e2' #color.base3


# eldrith-theme

# [colors.primary]
# background = '#212337'
# foreground = '#ebfafa'
#
# [colors.cursor]
# cursor = '#37f499'
# text = '#f8f8f2'
#
# [colors.normal]
# black = '#21222c'
# blue = '#9071f4'
# cyan = '#04d1f9'
# green = '#37f499'
# magenta = '#f265b5'
# red = '#f9515d'
# white = '#ebfafa'
# yellow = '#e9f941'
#
# [colors.bright]
# black = '#7081d0'
# blue = '#a48cf2'
# cyan = '#66e4fd'
# green = '#69f8b3'
# magenta = '#fd92ce'
# red = '#f16c75'
# white = '#ffffff'
# yellow = '#f1fc79'
#
# [colors.selection]
# background = '#bf4f8e'
# text = '#ebfafa'
